apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: attachedconnectors.skupper.io
  description:  |
      Skupper allows a site to target pods in other namespaces. It requires two new 
      resource types. The AttachedConnector resource is declared in the 
      namespace where the pods to be tracked are running. 
      It is largely similar to the Connector resource, but has a 
      siteNamespace field that identifies the site in which it is desired 
      that the pods being tracked are used to configure connectors. 
      The other new resource type is the AttachedConnectorAnchor. This is 
      created in the namespace of the site for which an AttachedConnector is 
      to be defined.
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                siteNamespace:
                  type: string
                port:
                  type: integer
                selector:
                  type: string
                tlsCredentials:
                  type: string
                type:
                  type: string
                includeNotReady:
                  type: boolean
              required:
              - port
              - selector
            status:
              type: object
              properties:
                active:
                  type: boolean
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Port
        type: integer
        description: The port to connect to
        jsonPath: .spec.port
      - name: Selector
        type: string
        description: The selector that identifies the pods to connect to
        jsonPath: .spec.selector
      - name: Site Namespace
        type: string
        description: The namespace in which the site this connector should be attached to is in
        jsonPath: .spec.siteNamespace
      - name: Active
        type: boolean
        description: Whether connector is active
        jsonPath: .status.active
      - name: Status
        type: string
        description: The status of the connector
        jsonPath: .status.status
  scope: Namespaced
  names:
    plural: attachedconnectors
    singular: attachedconnector
    kind: AttachedConnector
